services:
  bukhorcha-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_URL_V1: ${VITE_APP_URL_V1}
    ports:
      - "8011:80"
    container_name: bukhorcha-admin
    restart: unless-stopped
